// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo0rEB0wBvDBQsWrdZYQ7SOlO80USFHwU',
    appId: '1:260193466912:web:c9699740c84c700c835a45',
    messagingSenderId: '260193466912',
    projectId: 'camerapp-40bfc',
    authDomain: 'camerapp-40bfc.firebaseapp.com',
    storageBucket: 'camerapp-40bfc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0rOJMrd7XpRd0P-c_44r6kcnACwD4Do8',
    appId: '1:260193466912:android:88bd31d5c2bd20ab835a45',
    messagingSenderId: '260193466912',
    projectId: 'camerapp-40bfc',
    storageBucket: 'camerapp-40bfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-9qpadRo76lHklSsyT6dBVl59UGtWrtQ',
    appId: '1:260193466912:ios:9ec7c6f52c1bef08835a45',
    messagingSenderId: '260193466912',
    projectId: 'camerapp-40bfc',
    storageBucket: 'camerapp-40bfc.firebasestorage.app',
    iosBundleId: 'com.example.cameraApp',
  );
}
